### PR TITLE
Travis 0.6.3

### PR DESCRIPTION
**Pull request by Aesylwinn**

### CODE REVIEW

**Comment by Aesylwinn** [comment]
> if (now - startTime >= 60s)

What is the 's' supposed to do? I've never seen something like that. Anyway, other than a build error, everything else seems to work.

**Comment by davidcernat** [comment]
It's this:

http://en.cppreference.com/w/cpp/chrono/operator%22%22s

**Comment by Aesylwinn** [comment]
Interesting, looks like we need c++14 support to be specified.

**Comment by Aesylwinn** [comment]
> /home/travis/build/TES3MP/openmw-tes3mp/apps/openmw-mp/./Script/Functions/../Types.hpp:100:15: note: 
candidate constructor not viable: no known conversion from 'void (ScriptFunc, const char *, char, const char *) noexcept' (aka 'void (unsigned long long (*)(), const char *, char, const char *) noexcept') to 'ScriptFunctionPointer' for 2nd argument constexpr ScriptFunctionData(const char* name, ScriptFunctionPointe...

clang doesn't want to cast this, there is probably a simple fix

**Comment by Aesylwinn** [comment]
Well, seeing how the code causing it to fail is not present in the master branch, it's probably not too important to fix. I'll allow the clang build to fail here, but re-enable it for the master branch once this gets there.

**Comment by Aesylwinn** [comment]
@Koncord Ready for review when you have the time.

**Comment by davidcernat** [comment]
0.6.3 is very much my responsibility, so I'm just going to go ahead and merge this in because everything in it looks fine to me.

**Pull request merged**
