### PR TITLE
Updated link to change log

### PR DESCRIPTION
**Pull request by jefhai**

### CODE REVIEW

**Comment by jefhai** [comment]
Actually looks like you're missing your own change log...

**Comment by Koncord** [comment]
Thank you! This line simply should to be removed.

**Comment by davidcernat** [comment]
Not everyone agrees:

https://github.com/TES3MP/openmw-tes3mp/blob/master/tes3mp-changelog.md

:P

**Comment by jefhai** [comment]
@davidcernat nicely done

**Pull request closed without merging**
